  spring:
    redis:
      host: 192.168.8.128
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springboot-even
      username: root
      password: root



