spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/kingsum?characterEncoding=UTF-8
    username: root
    password: root
  data:
    mongodb:
      uri: mongodb://localhost:27017/kingsum
server:
  port: 10000
